project:
  name: "inventory-service"
  tech_stack: "java"  # python/nodejs/dotnet/cpp
  build_tool: "maven" # gradle/npm/pip/make
  deployment: "docker" # terraform/sam/cloudformation

workflow:
  stages:
    - lint
    - test
    - security-scan
    - build
    - deploy

branching:
  default_branch: "main"
  protected_branches: ["main", "release/*"]
  versioning: "semver"
